 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sisters", type: :request do
  
  # Sister. As you add validations to Sister, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Sister.create! valid_attributes
      get sisters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sister = Sister.create! valid_attributes
      get sister_url(sister)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sister_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sister = Sister.create! valid_attributes
      get edit_sister_url(sister)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sister" do
        expect {
          post sisters_url, params: { sister: valid_attributes }
        }.to change(Sister, :count).by(1)
      end

      it "redirects to the created sister" do
        post sisters_url, params: { sister: valid_attributes }
        expect(response).to redirect_to(sister_url(Sister.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sister" do
        expect {
          post sisters_url, params: { sister: invalid_attributes }
        }.to change(Sister, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sisters_url, params: { sister: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sister" do
        sister = Sister.create! valid_attributes
        patch sister_url(sister), params: { sister: new_attributes }
        sister.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sister" do
        sister = Sister.create! valid_attributes
        patch sister_url(sister), params: { sister: new_attributes }
        sister.reload
        expect(response).to redirect_to(sister_url(sister))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sister = Sister.create! valid_attributes
        patch sister_url(sister), params: { sister: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sister" do
      sister = Sister.create! valid_attributes
      expect {
        delete sister_url(sister)
      }.to change(Sister, :count).by(-1)
    end

    it "redirects to the sisters list" do
      sister = Sister.create! valid_attributes
      delete sister_url(sister)
      expect(response).to redirect_to(sisters_url)
    end
  end
end
